// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// roboBayesFirst
List roboBayesFirst(const arma::mat& datapts, const arma::mat& covariates, const Rcpp::List& paramsList);
RcppExport SEXP _roboBayes_roboBayesFirst(SEXP dataptsSEXP, SEXP covariatesSEXP, SEXP paramsListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type datapts(dataptsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type paramsList(paramsListSEXP);
    rcpp_result_gen = Rcpp::wrap(roboBayesFirst(datapts, covariates, paramsList));
    return rcpp_result_gen;
END_RCPP
}
// roboBayesPrior
List roboBayesPrior(const arma::mat& datapts, const arma::mat& covariates, const Rcpp::List& RoboBayes, const Rcpp::List& paramsList);
RcppExport SEXP _roboBayes_roboBayesPrior(SEXP dataptsSEXP, SEXP covariatesSEXP, SEXP RoboBayesSEXP, SEXP paramsListSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type datapts(dataptsSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type RoboBayes(RoboBayesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type paramsList(paramsListSEXP);
    rcpp_result_gen = Rcpp::wrap(roboBayesPrior(datapts, covariates, RoboBayes, paramsList));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_roboBayes_roboBayesFirst", (DL_FUNC) &_roboBayes_roboBayesFirst, 3},
    {"_roboBayes_roboBayesPrior", (DL_FUNC) &_roboBayes_roboBayesPrior, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_roboBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
