# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

roboBayesFirst <- function(datapts, covariates, paramsList) {
    .Call('_roboBayes_roboBayesFirst', PACKAGE = 'roboBayes', datapts, covariates, paramsList)
}

roboBayesPrior <- function(datapts, covariates, RoboBayes, paramsList) {
    .Call('_roboBayes_roboBayesPrior', PACKAGE = 'roboBayes', datapts, covariates, RoboBayes, paramsList)
}

